italian=["maison thomas", "Lucca", "piazzini", "olivo", "vapiano","cucina"]
american=["lucilles", "longhorn texas bbq", "sizzler", "fuddruckers", "chicken & ribs"]
french=["paul", "brioche duree", "amelie", "the smokery" ]
asian=["kazoku", "yana", "mahraja", "tao", "garnell"]
mexican=["gringos" ,"el chico", "tacos", "bonita", "hola"]
seafood=["asmak", "clams and claws", "beluga", "tarh al bahr", "elborg" ]
arabic=["arabiata", "tabali", "kababgy", "aroz", "antique" ]
baristas = ['Peppermint', 'dunkin donuts', 'krispy kream', 'second cup', 'thirty north', 'coffee corner',' espresso lab', 'TBS', 'Starbucks', 'Costa']    breakfast = ['Tabaly', 'Qahwa', 'Ovio', 'Loft', '3eesh wee Gebny', 'Paul', ]
cuisines = ["italian","american","french","asian","mexican","seafood","oriental"]
